# Generated by Django 4.2.1 on 2023-11-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='creation date'),
        ),
    ]
