# Generated by Django 4.2.1 on 2023-11-16 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
