# Generated by Django 4.2.1 on 2023-11-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='value',
        ),
        migrations.AddField(
            model_name='answer',
            name='text_value',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
