# Generated by Django 4.2.1 on 2023-11-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_choice_is_text_alter_answer_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
