# Generated by Django 4.2.1 on 2023-11-14 17:58

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('polls', '0008_dropdown_multiplechoice_poll_starrating_subjective_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name = 'Question',
            fields = [
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('content_type', models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_object', GenericForeignKey('content_type', 'object_id'))
            ]
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_length', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.DeleteModel(
            name='DropDown',
        ),
        migrations.DeleteModel(
            name='MultipleChoice',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='StarRating',
        ),
        migrations.DeleteModel(
            name='Subjective',
        ),
        migrations.AddField(
            model_name='question',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='question',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
