# Generated by Django 4.2.1 on 2023-11-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_multiplechoicequestion_questiontype_textquestion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleChoiceQuestion',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
        migrations.DeleteModel(
            name='TextQuestion',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
